In [1]:
import numpy as np

In [2]:
x=np.array([1,1,1],dtype=np.float32)

In [3]:
x

array([1., 1., 1.], dtype=float32)

In [4]:
x.itemsize

4

In [5]:
np.sin(np.array([1,1,1],dtype=np.float32))

array([0.84147096, 0.84147096, 0.84147096], dtype=float32)

In [6]:
x=np.array([ [1,2,3],[4,5,6] ])

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x[:,0]

array([1, 4])

In [9]:
x[:,1]

array([2, 5])

In [10]:
x[:,2]

array([3, 6])

In [11]:
x[0,:]

array([1, 2, 3])

In [12]:
x[1,:]

array([4, 5, 6])

In [13]:
x=np.array([ [1,2,3],[4,5,6] ])

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x[:,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x[:,::2]

array([[1, 3],
       [4, 6]])

In [17]:
x=np.ones((3,3))
x[0,0]=2
x[1,1]=3
x[2,2]=4
x

array([[2., 1., 1.],
       [1., 3., 1.],
       [1., 1., 4.]])

In [18]:
x[:,[0,1,2,0]]

array([[2., 1., 1., 2.],
       [1., 3., 1., 1.],
       [1., 1., 4., 1.]])

In [19]:
y=x[:,[0,1,2,0]]
y

array([[2., 1., 1., 2.],
       [1., 3., 1., 1.],
       [1., 1., 4., 1.]])

In [20]:
x[1,1]=6
x

array([[2., 1., 1.],
       [1., 6., 1.],
       [1., 1., 4.]])

In [21]:
y

array([[2., 1., 1., 2.],
       [1., 3., 1., 1.],
       [1., 1., 4., 1.]])

In [22]:
x = np.ones((3,3))
y = x[:2,:2] # upper left piece
x[0,0] = 998 # change value
x

array([[998.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [23]:
y

array([[998.,   1.],
       [  1.,   1.]])

In [24]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [25]:
y=x[[0,1,2]]
y

array([0, 1, 2])

In [26]:
z=x[:3]
z

array([0, 1, 2])

In [27]:
x[0]=999

In [28]:
x

array([999,   1,   2,   3,   4])

In [29]:
y

array([0, 1, 2])

In [30]:
z

array([999,   1,   2])

In [31]:
x.flags.owndata

True

In [32]:
y.flags.owndata

True

In [33]:
z.flags.owndata

False

In [34]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x=np.matrix([[1],[0],[0]])
A*x

matrix([[1],
        [4],
        [7]])

In [35]:
A=np.ones((3,3))
A[1,1]=2
type(A)

numpy.ndarray

In [36]:
x=np.ones((3,1)) # array not matrix
x[1,0]=2
A*x #element wise multiplication

array([[1., 1., 1.],
       [2., 4., 2.],
       [1., 1., 1.]])

In [37]:
X,Y=np.meshgrid(np.arange(2),np.arange(2))
X

array([[0, 1],
       [0, 1]])

In [38]:
Y

array([[0, 0],
       [1, 1]])

In [39]:
X+Y

array([[0, 1],
       [1, 2]])

In [40]:
x = np.array([0,1])
y = np.array([0,1])
x

array([0, 1])

In [41]:
y

array([0, 1])

In [42]:
x+y

array([0, 2])

In [43]:
z=y[:,None]
z

array([[0],
       [1]])

In [44]:
x = np.array([0,1])
y = np.array([0,1,2])
X,Y = np.meshgrid(x,y)
X

array([[0, 1],
       [0, 1],
       [0, 1]])

In [45]:
Y

array([[0, 0],
       [1, 1],
       [2, 2]])

In [46]:
X+Y

array([[0, 1],
       [1, 2],
       [2, 3]])

In [47]:
x+y[:,None]

array([[0, 1],
       [1, 2],
       [2, 3]])

In [48]:
x = np.array([0,1])
y = np.array([0,1,2])
z = np.array([0,1,2,3])
x+y[:,None]

array([[0, 1],
       [1, 2],
       [2, 3]])

In [49]:
x+y[:,None]+z[:,None,None]

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6]]])

In [50]:
import matplotlib.pyplot as plt
plt.plot(range(10))

In [51]:
plt.show()